# Generated by Django 2.2.7 on 2020-01-25 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0003_auto_20200119_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='dealer_id',
            new_name='dealership',
        ),
        migrations.RemoveField(
            model_name='job',
            name='cust_id',
        ),
        migrations.AddField(
            model_name='job',
            name='car_make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='seller',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
