# Generated by Django 2.2.7 on 2020-02-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20200131_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='customer_contacted',
            field=models.BooleanField(default=False),
        ),
    ]
